---
- hosts: 172.31.4.209
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: install webserver
      apt:
        name: apache2
        state: present

    - name: i want copy mytestfile into node side
      copy:
        src: mytestfile
        dest: /home/ubuntu/mytestfile


    - name: i want copy index.j2 file into node side
      template:
        src: myindex.j2
        dest: /var/www/html/index.html
      notify: restartwebservers

    handlers:
    - name: restartwebservers
      service:
         name: apache2
         state: restarted         
