---
- hosts: webserver
  tasks:
    - name: i want to install webserver
      apt:
        name: "{{apachesoft}}"
        state: present
      when: ansible_os_family=="Debian"

    - name: i want to start webserver
      service:
        name: "{{apachesoft}}"
        state: started
      when: ansible_os_family=="Debian"
