---
- hosts: 172.31.4.209
  become: yes
  vars:
    myvar01: git
    myvar02: tree
    myvar03: wget
  tasks:
    - name: i want to display myvar01 output
      debug:
        outputMyvar01: "{{myvar01}}"
        outputMyvar02: "{{myvar02}}"
        outputMyvar03: "{{myvar03}}"
